schemes:
  onelight: &onelight
    primary:
      # background: '#f8f8f8'
      background: '#eeeeee'
      foreground: '#2a2b33'
    normal:
      black:   '#000000'
      red:     '#de3d35'
      green:   '#3e953a'
      yellow:  '#d2b67b'
      blue:    '#2f5af3'
      magenta: '#950095'
      cyan:    '#3e953a'
      white:   '#bbbbbb'
    bright:
      black:   '#000000'
      red:     '#de3d35'
      green:   '#3e953a'
      yellow:  '#d2b67b'
      blue:    '#2f5af3'
      magenta: '#a00095'
      cyan:    '#3e953a'
      white:   '#ffffff'
  nord: &nord
    primary:
      background: '#2E3440'
      foreground: '#D8DEE9'
    normal:
      black:   '#3B4252'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#88C0D0'
      white:   '#E5E9F0'
    bright:
      black:   '#4C566A'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#8FBCBB'
      white:   '#ECEFF4'
  gruvbox: &gruvbox
    primary:
      background: '#282828'
      foreground: '#ebdbb2'
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
  solarizeddark: &solarizeddark
    primary:
      background: '#002b36' # base03
      foreground: '#839496' # base0
    cursor:
      text:   '#002b36' # base03
      cursor: '#839496' # base0
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3
  solarizedlight: &solarizedlight
    primary:
      background: '#fdf6e3'
      foreground: '#586e75'
    normal:
      black:   '#073642'
      red:     '#dc322f'
      green:   '#859900'
      yellow:  '#b58900'
      blue:    '#268bd2'
      magenta: '#d33682'
      cyan:    '#2aa198'
      white:   '#eee8d5'
    bright:
      black:   '#002b36'
      red:     '#cb4b16'
      green:   '#586e75'
      yellow:  '#657b83'
      blue:    '#839496'
      magenta: '#6c71c4'
      cyan:    '#93a1a1'
      white:   '#fdf6e3'

colors: *solarizedlight
# colors: *onelight

window:
  opacity: 1

font:
  normal:
    family: FiraCode Nerd Font Mono
  bold:
    family: FiraCode Nerd Font Mono
  italic:
    family: FiraCode Nerd Font Mono
  size: 11.0

key_bindings:
  - { key: Right,  mods: Alt,           chars: "\x1bf"                      }
  - { key: Left,  mods: Alt,           chars: "\x1bb"                       }
